spring:
  application:
    name: mariana

server:
  port: 10001

app:
  movie:
    directory:
      temporary: {TEMP_DIR}
      mariana: {MARIANA_DIR}
      akureyri: {AKUREYRI_DIR}

studio:
  caribbeancom:
    name: Caribbeancom
    japaneseName: カリビアンコム
    prefix: Carib
    uri: https://www.caribbeancom.com
    trailer: https://smovie.caribbeancom.com/sample/movies/{code}/{resolution}.mp4
    moviepages: /moviepages/{code}/index.html
    gallery: /moviepages/{code}/images/gallery.zip
    poster: /moviepages/{code}/images/l_l.jpg
  pondo:
    name: 1Pondo
    japaneseName: 一本道
    prefix: 1Pon
    uri: https://www.1pondo.tv
    movieDetails: /dyn/phpauto/movie_details/movie_id/{code}.json
    movieGallery: /dyn/dla/json/movie_gallery/{code}.json
    movieGalleries: /dyn/phpauto/movie_galleries/movie_id/{code}.json
  mus:
    name: 10musume
    japaneseName: 天然むすめ
    prefix: 10mu
    uri: https://www.10musume.com
    movieDetails: /dyn/phpauto/movie_details/movie_id/{code}.json
    movieGallery: /dyn/dla/json/movie_gallery/{code}.json
    movieGalleries: /dyn/phpauto/movie_galleries/movie_id/{code}.json
  heyzo:
    name: Heyzo
    japaneseName: Heyzo
    prefix: Heyzo
    uri: https://heyzo.com
    uriEn: https://en.heyzo.com
    trailer: /contents/3000/{code}/sample.mp4
    moviepages: /moviepages/{code}/index.html
    poster: /contents/3000/{code}/images/player_thumbnail.jpg
    gallery:
      jjgirls: https://jjgirls.com/uncensored/heyzo/{actor}/{code}/{actor}-{currentPhotoNumber}.jpg
  girlsDelta:
    name: GirlsDelta
    japaneseName: GirlsDelta
    prefix: GirlsDelta
    uri: https://girlsdelta.com
    product: /product/{code}
    trailer: /pics/product/{movieSecretId}/movie.mp4
    poster: /pics/product/{movieSecretId}/product_top.webp
    cashUri: http://cash.girlsdelta.com
    gallery: /gallery/delta/images/prod/{movieSecretId}/sample/{currentPhotoNumber}.jpg
