spring:
  application:
    name: mariana

server:
  port: 10001

studio:
  caribbeancom:
    name: Caribbeancom
    prefix: Carib
    uri: https://www.caribbeancom.com
    trailer: https://smovie.caribbeancom.com/sample/movies/{code}/{resolution}.mp4
    moviepages: /moviepages/{code}/index.html
    gallery: /moviepages/{code}/images/gallery.zip
    poster: /moviepages/{code}/images/l_l.jpg
